In [4]:
from scipy import sparse

eye = np.eye(4)
print( eye )

[[ 1.  0.  0.  0.]
 [ 0.  1.  0.  0.]
 [ 0.  0.  1.  0.]
 [ 0.  0.  0.  1.]]


In [5]:
# CSR format sparse mat
# only stores non-zeros
sp_mat = sparse.csr_matrix(eye)

print( sp_mat )

  (0, 0)	1.0
  (1, 1)	1.0
  (2, 2)	1.0
  (3, 3)	1.0


In [6]:
y = np.array( [ [0,0,0,1], [5,0,1,2], [0,0,6,0]])
print( sparse.csr_matrix(y) )

  (0, 3)	1
  (1, 0)	5
  (1, 2)	1
  (1, 3)	2
  (2, 2)	6
